# Generated by Django 6.0.1 on 2026-01-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reject_reason',
            field=models.CharField(blank=True, choices=[('Not Available', 'Doctor not available'), ('Emergency', 'Doctor in emergency'), ('Time Conflict', 'Time conflict'), ('Invalid Details', 'Invalid patient details'), ('Clinic Closed', 'Clinic closed'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
